"""
Модуль для тестовой конфигурации, который можно использовать в тестах
"""

from config.configs import Config, Scheduler, ExponentialSmoothing, Neuralprophet, Prophet, Theta, Arima, Timesfm, \
    _Scheduler, _ExponentialSmoothingModel, _ExponentialSmoothingTrain, _NeuralprophetModel, _NeuralprophetTrain, \
    _ProphetModel, _ProphetTrain, _ThetaModel, _ThetaTrain, _ArimaModel, _ArimaTrain, _TimesfmModel, _TimesfmTrain


def get_test_config():
    """
    Возвращает объект конфигурации для использования в тестах
    """
    return Config(
        n_forecasts=13,
        optuna_n_trials=10,
        cross_validation_k_folds=4,
        outliers_sliding_window_size=12,
        use_only_light_models=False,
        min_unique_points=2,
        freq='W-MON',
        years_of_historical_data=3,
        neuralprophet=Neuralprophet(
            model=_NeuralprophetModel(
                drop_missing=True,
                unknown_data_normalization=True,
                trend_global_local='local',
                season_global_local='local',
                yearly_seasonality=True,
                weekly_seasonality=False,
                daily_seasonality=False,
                learning_rate=1e-4,
                n_lags=13,
                n_forecasts=13
            ),
            train=_NeuralprophetTrain(
                ew_lag=3,
                freq='W-MON',
                n_epochs=30
            )
        ),
        exponential_smoothing=ExponentialSmoothing(
            model=_ExponentialSmoothingModel(
                seasonal_periods=52,
                trend='additive',
                seasonal='additive',
                damped_trend=False,
                use_boxcox=False,
                freq='W-MON'
            ),
            train=_ExponentialSmoothingTrain(
                ew_lag=3
            )
        ),
        prophet=Prophet(
            model=_ProphetModel(
                growth='linear',
                n_changepoints=25,
                changepoint_range=0.8,
                yearly_seasonality=True,
                weekly_seasonality='auto',
                daily_seasonality='auto',
                seasonality_mode='additive',
                seasonality_prior_scale=10.0,
                holidays_prior_scale=10.0,
                changepoint_prior_scale=0.05,
                holidays_mode='additive'
            ),
            train=_ProphetTrain(
                ew_lag=3
            )
        ),
        theta=Theta(
            model=_ThetaModel(
                period=52
            ),
            train=_ThetaTrain(
                theta=2,
                ew_lag=3,
                use_mle=True,
                freq='W-MON'
            )
        ),
        arima=Arima(
            model=_ArimaModel(
                p=1,
                d=1,
                q=0,
                P=1,
                D=1,
                Q=0,
                s=53,
                simple_differencing=False,
                fit_intercept=True
            ),
            train=_ArimaTrain(
                method='css',
                freq='W-MON'
            )
        ),
        timesfm=Timesfm(
            model=_TimesfmModel(
                model_name='google/timesfm-2.5-200m-pytorch',
                max_context=1024,
                normalize_inputs=True,
                use_continuous_quantile_head=True,
                infer_is_positive=True
            ),
            train=_TimesfmTrain(
                ew_lag=0,
                freq='W-MON',
                period=52
            )
        ),
        scheduler=Scheduler(
            forecasting=_Scheduler(
                day_of_week='sat',
                hour=21,
                minute=0
            ),
            dashboards=_Scheduler(
                day_of_week='sun',
                hour=20,
                minute=0
            )
        ),
        macroeconomic_indicators=[],
        agro_indicators=[],
        agro_indicators_product_categories=[],
        meat_products=None,
        seafood_products=None,
        caviar_products=None,
        fish_products=None,
        shrimp_products=None,
        semiprocessed_products=None
    )
