n_forecasts: 13
optuna_n_trials: 10
cross_validation_k_folds: 3
outliers_sliding_window_size: 12
use_only_light_models: False
min_unique_points: 2
freq: 'W-MON'
years_of_historical_data: 3

neuralprophet:
  model:
    drop_missing: True
    unknown_data_normalization: True
    trend_global_local: 'local'
    season_global_local: 'local'
    yearly_seasonality: True
    weekly_seasonality: False
    daily_seasonality: False
    learning_rate: 1e-4
    n_lags: 13
    n_forecasts: 13
  train:
    ew_lag: 3
    freq: 'W-MON'
    n_epochs: 30
    period: 52


exponential_smoothing:
  model:
    seasonal_periods: 52
    trend: 'additive'
    seasonal: 'additive'
    damped_trend: False
    use_boxcox: False
    freq: 'W-MON'
  train:
    ew_lag: 3

prophet:
  model:
    growth: 'linear'
    n_changepoints: 25
    changepoint_range: 0.8
    yearly_seasonality: True
    weekly_seasonality: 'auto'
    daily_seasonality: 'auto'
    seasonality_mode: 'additive'
    seasonality_prior_scale: 10.0
    holidays_prior_scale: 10.0
    changepoint_prior_scale: 0.05
    holidays_mode: 'additive'
  train:
    period: 52
    ew_lag: 3
    freq: 'W-MON'

theta:
  model:
    period: 52
  train:
    theta: 2
    ew_lag: 3
    use_mle: True
    freq: 'W-MON'

arima:
  model:
    p: 1 # сколько прошлых значений ряда используется для предсказания текущего
    d: 1 # Сколько раз нужно взять разность ряда, чтобы он стал стационарным. d=0 — ряд уже стационарен. d=1 — берётся первая разность d=2 — разность разности и т.д.
    q: 0 # сколько прошлых ошибок (шумов) модели учитывается.
    P: 1 # сезонный порядок авторегрессии (SAR). P=1 означает, что значение в текущем сезоне зависит от значения в том же периоде прошлого
    D: 0 # сезонный порядок интегрирования (разность)
    Q: 0 # сезонный порядок скользящего среднего (SMA). Q=1 означает, что ошибка модели зависит от ошибки, сделанной в том же сезоне прошлого года
    s: 52 # длина сезонного цикла
    simple_differencing: True
    fit_intercept: False
  train:
    method: 'css'
    freq: 'W-MON'

timesfm:
  model:
    model_name: 'google/timesfm-2.5-200m-pytorch'
    max_context: 1024
    normalize_inputs: True
    use_continuous_quantile_head: True
    infer_is_positive: True
  train:
    ew_lag: 0
    freq: 'W-MON'
    period: 52

scheduler:
  forecasting:
    day_of_week: 'sat'
    hour: 21
    minute: 0
  dashboards:
    day_of_week: 'sun'
    hour: 20
    minute: 0

meat_products:
  - name: 'Говядина полутуши'
    product:
      - 'Говядина'
    product_type:
      - 'полутуши'

  - name: 'Говядина грудинка'
    product:
      - 'Говядина'
    product_type:
      - 'грудинка'

  - name: 'Говядина лопатка'
    product:
      - 'Говядина'
    product_type:
      - 'лопатка'

  - name: 'Говядина вырезка'
    product:
      - 'Говядина'
    product_type:
      - 'вырезка'

  - name: 'Говядина тримминг'
    product:
      - 'Говядина'
    product_type:
      - 'тримминг'

  - name: 'Говядина передние четверти'
    product:
      - 'Говядина'
    product_type:
      - 'передние четверти'

  - name: 'Говядина задние части'
    product:
      - 'Говядина'
    product_type:
      - 'задние части'

  - name: 'Говядина глазной мускул'
    product:
      - 'Говядина'
    product_type:
      - 'глазной мускул'

  - name: 'Говядина печень'
    product:
      - 'Говядина'
    product_type:
      - 'печень'

  - name: 'Свинина полутуши'
    product:
      - 'Свинина'
    product_type:
      - 'полутуши'

  - name: 'Свинина шея'
    product:
      - 'Свинина'
    product_type:
      - 'шея'

  - name: 'Свинина корейка'
    product:
      - 'Свинина'
    product_type:
      - 'корейка'

  - name: 'Свинина лопатка'
    product:
      - 'Свинина'
    product_type:
      - 'лопатка'

  - name: 'Свинина окорок'
    product:
      - 'Свинина'
    product_type:
      - 'окорок'

  - name: 'Свинина ребро'
    product:
      - 'Свинина'
    product_type:
      - 'ребро'

  - name: 'Свинина грудинка'
    product:
      - 'Свинина'
    product_type:
      - 'грудинка'

  - name: 'Свинина карбонад'
    product:
      - 'Свинина'
    product_type:
      - 'карбонад'

  - name: 'Свинина рулька'
    product:
      - 'Свинина'
    product_type:
      - 'рулька'

  - name: 'Свинина тримминг'
    product:
      - 'Свинина'
    product_type:
      - 'тримминг'

  - name: 'Свинина фарш'
    product:
      - 'Свинина'
    product_type:
      - 'фарш'

  - name: 'Кура тушка'
    product:
      - 'Кура'
    product_type:
      - 'тушка'

  - name: 'Кура голень'
    product:
      - 'Кура'
    product_type:
      - 'голень'

  - name: 'Кура бедро'
    product:
      - 'Кура'
    product_type:
      - 'бедро'

  - name: 'Кура филе бедра'
    product:
      - 'Кура'
    product_type:
      - 'филе бедра'

  - name: 'Кура филе грудки'
    product:
      - 'Кура'
    product_type:
      - 'филе грудки'

  - name: 'Кура крыло'
    product:
      - 'Кура'
    product_type:
      - 'крыло'

  - name: 'Кура желудки'
    product:
      - 'Кура'
    product_type:
      - 'желудки'

  - name: 'Кура грудка'
    product:
      - 'Кура'
    product_type:
      - 'грудка'

  - name: 'Кура печень'
    product:
      - 'Кура'
    product_type:
      - 'печень'

  - name: 'Кура фарш'
    product:
      - 'Кура'
    product_type:
      - 'фарш'

  - name: 'Кура шея'
    product:
      - 'Кура'
    product_type:
      - 'шея'

  - name: 'Индейка филе грудки'
    product:
      - 'Индейка'
    product_type:
      - 'филе грудки'

  - name: 'Индейка филе бедра'
    product:
      - 'Индейка'
    product_type:
      - 'филе бедра'

  - name: 'Индейка крыло'
    product:
      - 'Индейка'
    product_type:
      - 'крыло'

  - name: 'Индейка голень'
    product:
      - 'Индейка'
    product_type:
      - 'голень'

  - name: 'Индейка бедро'
    product:
      - 'Индейка'
    product_type:
      - 'бедро'

seafood_products:
  - name: 'кальмар'
    product_type:
      - 'кальмар гигантский'
    goods_type:
      - 'филе'

  - name: 'мидии'
    product_type:
      - 'мидии'
    goods_type:
      - 'мясо'

  - name: 'вонголе'
    product_type:
      - 'вонголе'
    goods_type:
      - 'мясо'

  - name: 'плавники кальмара'
    product_type:
      - 'кальмар'
    goods_type:
      - Null
    cutting:
      - '%с плавником%'

caviar_products:
  - name: 'горбуша'
    product_type:
      - 'горбуша'

fish_products:
  - name: 'горбуша'
    fish_type:
      - 'горбуша'
    product_type:
      - 'целый'
      - 'тушка'
      - Null
    cutting:
      - '%потр%'

  - name: 'форель'
    fish_type:
      - 'форель'
    product_type:
      - 'стейк'

shrimp_products:
  - name: 'креветки очищенные'
    product_type:
      - Null
    cutting:
      - '%очищенные%'


semiprocessed_products:
  - name: 'кета пресервы'
    fish_type:
      - 'кета'
    cook_method:
      - 'Пресервы'

  - name: 'Сельдь пресервы'
    fish_type:
      - 'сельдь'
    cutting:
      - '%филе%'
      - Null
    cook_method:
      - 'Пресервы'
    filling:
      - 'в масле'
      - 'в маринаде'
      - 'со специями'
      - 'в заливке'
      - 'с овощами'
      - 'в соусе'
      - Null


macroeconomic_indicators:
  - 'ВВП'
  - 'Индекс пром.производства'
  - 'Цены производителей пром.товаров'
  - 'Производство пищевых продуктов'
  - 'Инфляция'
  - 'Индекс реальной зарплаты'

agro_indicators:
  - 'Поголовье скота и птицы'
  - 'Средние цены производителей промышленных товаров с 2017 г. '
  - 'Средние цены производителей сельскохозяйственной продукции, реализуемой сельскохозяйственными организациями с 2017 г. '
  - 'Производство основных видов продукции в натуральном выражении  с 2017 г. (оперативные данные в соответствии с ОКПД2)'
  - 'Наличие кормов'
  - 'Наличие концентрированных кормов'
  - 'Остатки продукции в сельскохозяйственных организациях с 2017 г.'

agro_indicators_product_categories:
  - 'Коровы'
  - 'Птица'
  - 'Свиньи'
  - 'Субпродукты сельскохозяйственной птицы, пригодные для употребления в пищу'
  - 'Скот и птица (в живом весе)'
  - 'Мясо крупного рогатого скота (говядина и телятина) замороженное, в том числе для детского питания'
  - 'Субпродукты пищевые свиные замороженные'
  - 'Свиньи для убоя'
  - 'Крупный рогатый скот для убоя'
  - 'Говядина парная, остывшая или охлажденная'
  - 'Мясо и субпродукты пищевые домашней птицы'
  - 'Продукты из мяса'
  - 'Продукты из мяса и мяса птицы'
  - 'Крупный рогатый скот'
  - 'Говядина замороженная'
  - 'Свинина замороженная'